# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
    - name: Zip Package
      run: |
        cd ${{ github.workspace }}/out
        zip -r ${{ github.workspace }}/out.zip . -x '*.git*'
    - name: Configure AWS Credentials
      id: aws-login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::322094740524:role/gh-actions-role
        aws-region: us-east-1
        output-credentials: true

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ steps.aws-login.outputs.aws-access-key-id }}
        aws_secret_key: ${{ steps.aws-login.outputs.aws-secret-access-key }}
        aws_session_token: ${{ steps.aws-login.outputs.aws-session-token }}
        application_name: RoutingTestAPI
        environment_name: sieslabs-dev
        region: us-east-1
        version_label: ${{ github.run_id }}
        version_description: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/out.zip
        
